apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: eks-devops-app
  namespace: devops-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: eks-devops-app-secret
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: eks-devops-app/prod
        property: APP_SECRET
