name: CI - AWS OIDC Test

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: eks-devops-app

jobs:
  aws-oidc-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: arn:aws:iam::866705901512:role/GitHubActionsEKSDevOpsRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-oidc
          allowed-account-ids: 866705901512

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
